version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - "admin_credentials.txt"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - 5444:5432
    restart: unless-stopped
    container_name: golang_db