version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - "app/admin_credentials.txt"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    container_name: golang_db
    networks:
      - blog

  app:
    build: app/
    ports:
      - "8888:8888"
    restart: unless-stopped
    container_name: golang_app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - blog

networks:
  blog:
